# Build Stage 1
FROM node:16-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
COPY .npmrc ./
COPY tsconfig.json ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# Build Stage 2
FROM node:16-alpine
RUN apk --no-cache add bash
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .
EXPOSE 4003
CMD [ "npm", "start" ]