apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{ if .Values.deployments.iamRoleArn -}}
    eks.amazonaws.com/role-arn: "{{ .Values.deployments.iamRoleArn }}"
    {{- end }}
  name: {{ .Values.deployments.name }}
  namespace: {{ .Values.namespace }}
