# External Secrets stored in AWS Secrets Manager (managed by Terraform), populated using the K8s-external-secrets service
# Source: https://github.com/godaddy/kubernetes-external-secrets
---

{{- if len .Values.external_secrets }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Values.deployments.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
  {{- range $k := .Values.external_secrets }}
  - key: "eks/{{ $.Values.namespace }}/{{ $.Values.deployments.name }}/{{ $k | upper }}"
    name: {{ $k | upper }}
  {{- end }}
{{- end -}}
