#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo \"Running yarn install...\"
yarn install

echo \"Running lint...\"

yarn lint:fix

echo \"Running type-check...\"

yarn type-check

echo \"Running prettier...\"

yarn format

